version: 2

updates:
  - package-ecosystem: terraform
    directory: "/terraform"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "【Terraform】"
      prefix-development: "[dev]"
      include: "scope"
