name: terraform validate
description: terraform validateを実行するアクション
inputs:
  terraform-version:
    description: 'terraform version'
    required: true
    default: ""
  working-directory:
    description: 'matrix.dir'
    required: true
    default: ""
runs:
  using: composite
  steps:
    - name: actions/checkout@v4
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
    - name: init
      shell: bash
      run: terraform init
      working-directory: ${{ inputs.working-directory }}
    - name: terraform validate
      shell: bash
      run: terraform validate -no-color # no-colorオプションを付けないと、GitHub Actionsのログに色がついてしまう
      working-directory: ${{ inputs.working-directory }}
