name: terraform fmt/validate
description: terraform fmt/validateを実行するアクション
inputs:
  working-directory:
    description: 'matrix.dir'
    required: true
    default: ""
runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.6
    - name: init
      shell: bash
      run: terraform init
      working-directory: ${{ inputs.working-directory }}
    - id: fmt
      run: terraform fmt -check -diff
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: terraform validate
      shell: bash
      run: terraform validate
      working-directory: ${{ inputs.working-directory }}
