name: terraform fmt/validate/plan

on:
  pull_request:
    types: [opened,synchronize,reopened] # PR作成時と変更時
    paths:
      - "route53/**"  # route53ディレクトリ以下の変更時
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: route53
    steps:
      # ソース取得
      - name: Checkout
        uses: actions/checkout@v3
      # AWSの権限設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN_PLAN }}
          aws-region: ap-northeast-1
      # 事前チェック（強制フォーマットとValidate）

      # Terraformのインストール
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6
      - name: init
        run: terraform init
      - name: terraform fmt
        run: terraform fmt -check -recursive
      - name: terraform validate
        run: terraform validate

      # plan実行(Composite Actionで呼び出す)
      - name: Terraform plan
        uses: ./.github/actions/terraform_plan/
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN_PLAN }}
