name: terraform fmt/validate/plan

on:
  pull_request:
    types: [opened,synchronize,reopened] # PR作成時と変更時、更新時に実行
    paths:
      - "terraform/**"  # terraformディレクトリの全サブディレクトリの変更時
jobs:
  create_changed_directory_list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-target.outputs.target_matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: fetch base branch (マージ先取得)
        run: git fetch origin ${{ github.base_ref }} --depth=1 # depth=1で最新のコミットのみ取得
      - name: Create list of modified directories
        id: set-target
        run: |
          # 変更されたディレクトリのリストを作成 
          # github.base_refはマージ先のブランチ名、HEADは現在のコミット、sed 's#/[^/]*$##'は#を区切り文字として、最後の/以降を削除する、uniqは重複を削除してディレクトリのみにする
          changed_dirs=$(git diff --name-only origin/${{ github.base_ref }} HEAD  | grep '^terraform/' | sed 's#/[^/]*$##' | uniq)
          echo "Changed directories: $changed_dirs"
          
          # JSON形式で出力
          echo "{\"include\":[$(echo $changed_dirs | sed 's/ /, /g' | sed 's/^/{\"dir\":\"/' | sed 's/$/\"}/' | sed 's/, /\"}, {\"dir\":\"/g')]}"
          echo "matrix={\"include\":[$(echo $changed_dirs | sed 's/ /, /g' | sed 's/^/{\"dir\":\"/' | sed 's/$/\"}/' | sed 's/, /\"}, {\"dir\":\"/g')]}" >> $GITHUB_OUTPUT
  run_tasks_for_changed_directories:
    runs-on: ubuntu-latest
    needs: create_changed_directory_list # 依存関係
    strategy:
      matrix: ${{fromJson(needs.create_changed_directory_list.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - name: RunTask
        run: |
          rcho "Running task for changed directory: ${{ matrix.dir }}}"
  # terraform:
  #   runs-on: ubuntu-latest
  #   environment: development
  #   permissions:
  #     id-token: write
  #     contents: write
  #     pull-requests: write
  #   strategy:
  #     matrix:
  #       dir: # 実行するディレクトリを指定する
  #       - "terraform/route53"
  #       - "terraform/ecr"
  #   steps:
  #     # ソース取得
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     # AWSの権限設定
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN_PLAN }}
  #         aws-region: ap-northeast-1
  #     # 事前チェック（強制フォーマットとValidate）
  #     - name: Terraform fmt/validate
  #       uses: ./.github/actions/terraform_check/
  #       with:
  #         working-directory: ${{ matrix.dir }}
  #     # plan実行(Composite Actionで呼び出す)
  #     - name: Terraform plan
  #       uses: ./.github/actions/terraform_plan/
  #       with:
  #         working-directory: ${{ matrix.dir }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
