name: terraform fmt/validate/plan

on:
  pull_request:
    types: [opened,synchronize,reopened] # PR作成時と変更時
    paths:
      - "terraform/**"  # terraformディレクトリ以下の変更時
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    strategy:
      matrix:
        dir: # 実行するディレクトリを指定する
        - "terraform/route53"
        - "terraform/ecr"
    steps:
      # ソース取得
      - name: Checkout
        uses: actions/checkout@v3
      # AWSの権限設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN_PLAN }}
          aws-region: ap-northeast-1
      # 事前チェック（強制フォーマットとValidate）
      - name: Terraform fmt/validate
        uses: ./.github/actions/terraform_check/
        with:
          working-directory: ${{ matrix.dir }}
      # plan実行(Composite Actionで呼び出す)
      - name: Terraform plan
        uses: ./.github/actions/terraform_plan/
        with:
          working-directory: ${{ matrix.dir }}
